Added Server Error Handling

diff --git a/bin/Autologin b/bin/Autologin
--- a/bin/Autologin
+++ b/bin/Autologin
@@ -2,6 +2,17 @@
 
 username="$(sed '2d' ./docs/creds/$Chat_Id/unilag_cred)"
 pass="$(sed '1d' ./docs/creds/$Chat_Id/unilag_cred)"
+
+check(){
+    status_code=$(curl -o /dev/null -s -w "%{http_code}\n" "http://studentportal.unilag.edu.ng/(S(lkynzhoc3fox21jdy343vwl0))/default.aspx")
+    [ $status_code -eq 302 ] || {
+        echo "Server Error"
+        exit 1
+    }
+    echo "Good"
+}
+
+details(){
 url=$(curl -s "http://studentportal.unilag.edu.ng/(S(lkynzhoc3fox21jdy343vwl0))/default.aspx")
 declare -i counter=1
 while read -r line || [[ -n $line ]]
@@ -19,7 +30,10 @@ event_validation=$(curl -s "http://studentportal.unilag.edu.ng$urrl/default.aspx
 curl -D - -s -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'Origin: http://studentportal.unilag.edu.ng' -H 'Upgrade-Insecure-Requests: 1' -H 'Content-Type: application/x-www-form-urlencoded' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.71 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Referer: http://studentportal.unilag.edu.ng/(S(lkynzhoc3fox21jdy343vwl0))/default.aspx' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.9' --data-urlencode "PasswordTextBox=$pass" --data-urlencode "UsernameTextBox=$username" --data-urlencode "__EVENTVALIDATION=$event_validation" --data-urlencode "__VIEWSTATE=$viewstate" --data-urlencode "__VIEWSTATEGENERATOR=$viewgen" "http://studentportal.unilag.edu.ng$urrl/StudentLoginPage.aspx" --compressed --insecure > output/$Chat_Id/header
 cookie=$(cat output/$Chat_Id/header | grep -i cookie | sed 's@.*Set-Cookie\:@@' | sed 's@\;.*@@')
 rm output/$Chat_Id/header
+}
+
 if [ "$1" == "courseform" -o -f output/$Chat_Id/temp ]; then
+    details
 reg=$(curl -s -L -H "Cookie: $cookie" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Encoding: " -H "Accept-Langauge: en-US,en;q=0.5" -H "Connection: keep-alive" -H "Host: studentportal.unilag.edu.ng" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"  "http://studentportal.unilag.edu.ng$urrl/RegistrationListPage.aspx")
 if [ ! -f output/$Chat_Id/temp ]; then
 echo "Choose Course Registration To Download" >> output/$Chat_Id/temp
@@ -44,9 +58,16 @@ url="PrintRegistrationPage.aspx?$y"
 curl -s -L -H "Cookie: $cookie" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Encoding: " -H "Accept-Langauge: en-US,en;q=0.5" -H "Connection: keep-alive" -H "Host: studentportal.unilag.edu.ng" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"  "http://studentportal.unilag.edu.ng$urrl/$url" -o output/$Chat_Id/CourseRegistration.pdf
 rm -rf output/$Chat_Id/temp
 fi
-elif [ "$1" == "verify" ]; then
+fi
+
+case $1 in 
+    "verify")
     curl -s -L -H "Cookie: $cookie" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Encoding: " -H "Accept-Langauge: en-US,en;q=0.5" -H "Connection: keep-alive" -H "Host: studentportal.unilag.edu.ng" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"  "http://studentportal.unilag.edu.ng$urrl/StudentHomePage.aspx" > output/$Chat_Id/stuff.html
     ver=$(cat output/$Chat_Id/stuff.html | grep -i -w welcome)
     echo $ver
     rm -rf output/$Chat_Id/stuff.html
-fi
+    ;;
+    "check")
+    echo $(check)
+    ;;
+esac
